### ISSUE TITLE
 some suggestions 

### ISSUE THREAD

**Issue by tt0576** [DerEffi/image-comparison#1]
The scanning speed is very fast and it is also very easy to use. Thank you. This is the function I want.

A few suggestions:

1. Should the previous button have some restrictions? I often click the wrong button and it will return to the previous search.

2. It seems that the first identical item cannot be automatically deleted.

3. The percentage setting here seems to automatically return to 0.1. You need to add 0.1 when setting it.

**Comment by itstheeffi** [comment]
Thank you very much for your interest in my App. I'm glad, that it is useful to you.

Also thank you for your suggestions:

1. Yes it seems like a good idea to prevent the previous button to abort the search on the first image pair.
2. Can you describe this issue further? I tried to replicate this behavior, but on my devices all images are deleted accordingly. Is that the case with all your searches or only with specific files? Is something else on your device preventing you from deleting it (If it can't delete it, it just skips it - better safe than sorry)? Is anything in the Logs section that may hint to the problem (If there is something be sure to blank out the file paths for privacy before posting it here)?
3. I could replicate your problem, but for me that only happens sometimes. It seems to be a problem with the slider on user input, since it returns to the value it actually saved in the background (sometimes 0.1 smaller than the input). I don't have a solution right now, but I will look further into that.

**Comment by itstheeffi** [comment]
So I now looked at the code and found the problem with the percentage sliders:
The UI had a different rounding behavior of a decimal place not directly shown than the underlying settings (they previously always rounded down), so once the settings updated in 50% of the cases it would look like jumping down by 0.1%.

Since I didn't hear back from you on your problem of deleting images automatically, I'm considering this issue closed.
As long as not more or wrong images are deleted I'm also not considering it a major issue, but if the problem persists and you have more information on that, so I can find the bug, feel free to open another issue.
